-- What is the total revenue generated?
SELECT ROUND(SUM(oi.quantity*oi.price_per_unit),2) AS total_revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status = 'Delivered';

-- How many orders were successfully delivered?
SELECT order_status, COUNT(order_status) FROM orders
WHERE order_status = 'Delivered';

-- What is the average order value?
SELECT ROUND(SUM(oi.quantity*oi.price_per_unit)/COUNT(DISTINCT(o.order_id)),2) AS average_order_value
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status = 'Delivered';

-- What is the total revenue generated by category?
SELECT p.category, SUM(oi.quantity*oi.price_per_unit) AS revenue
FROM order_items oi 
INNER JOIN products p
ON oi.product_id = p.product_id
INNER JOIN orders o
ON o.order_id = oi.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.category
ORDER BY revenue DESC;

-- Who are the top 10 customers by Revenue?
SELECT c.customer_id, SUM(oi.quantity*oi.price_per_unit) as total_spent
FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
INNER JOIN order_items oi
ON oi.order_id = o.order_id 
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_id
ORDER BY total_spent DESC
LIMIT 10;

-- What is the revenue generated per month?
SELECT DATE_FORMAT(o.order_date, '%Y-%m') AS `month`,
SUM(oi.quantity*oi.price_per_unit) AS revenue
FROM orders o
INNER JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY `month`
ORDER BY `month`;

-- What is the most expensive Product?
SELECT * FROM products 
WHERE price = (SELECT MAX(price) FROM products);

-- Categorize Orders as small, medium or large
SELECT order_id, SUM(quantity*price_per_unit) AS order_total,
CASE 
	WHEN SUM(quantity*price_per_unit) < 5000 THEN 'Small'
    WHEN SUM(quantity*price_per_unit) BETWEEN 5000 AND 15000 THEN 'Mediumn'
    ELSE 'Large'
END AS order_size
FROM order_items
GROUP BY order_id;

-- What are the TOP 5 products by revenue?
SELECT p.product_name, SUM(oi.quantity*oi.price_per_unit) AS revenue
FROM order_items oi
INNER JOIN products p
ON oi.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY revenue ASC
LIMIT 5;

-- Rank the Top 10 customers by spending
SELECT customer_id,
SUM(oi.quantity * oi.price_per_unit) AS total_spent,
RANK() OVER (ORDER BY SUM(oi.quantity * oi.price_per_unit) DESC) AS rank_position
FROM orders o
JOIN order_items oi 
ON o.order_id = oi.order_id
GROUP BY customer_id
LIMIT 10;